server:
  servlet:
    context-path: "/spring-app"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database-name

logging:
  level:
    com.zaxxer.hikari.HikariConfig: TRACE
    com.zaxxer.hikari: TRACE
    org.springframework.jdbc: DEBUG
